import yaml from 'js-yaml';
import type { Proxy } from '../types';

interface MihomoConfig {
    proxies: Proxy[];
    'proxy-groups': ProxyGroup[];
    rules: string[];
}

interface ProxyGroup {
    name: string;
    type: string;
    url?: string;
    interval?: number;
    tolerance?: number;
    proxies: string[];
}

/**
 * Generate a complete Mihomo configuration YAML from an array of proxies.
 */
export function generateMihomoConfig(proxies: Proxy[]): string {
    if (proxies.length === 0) {
        return yaml.dump({ proxies: [] }, { lineWidth: -1 });
    }

    const proxyNames = proxies.map((p) => p.name);

    const config: MihomoConfig = {
        proxies: proxies,
        'proxy-groups': [
            {
                name: 'Proxy',
                type: 'select',
                proxies: ['Auto', 'Fallback', ...proxyNames],
            },
            {
                name: 'Auto',
                type: 'url-test',
                url: 'http://www.gstatic.com/generate_204',
                interval: 300,
                tolerance: 50,
                proxies: proxyNames,
            },
            {
                name: 'Fallback',
                type: 'fallback',
                url: 'http://www.gstatic.com/generate_204',
                interval: 300,
                proxies: proxyNames,
            },
        ],
        rules: ['MATCH,Proxy'],
    };

    return (
        '# Mihomo Configuration\n' +
        '# Generated by mihomo-converter\n\n' +
        yaml.dump(config, {
            lineWidth: -1, // Don't wrap lines
            quotingType: '"',
            forceQuotes: false,
            noRefs: true, // Disable anchors/aliases
        })
    );
}
